version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/node_modules/bcrypt
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
    depends_on:
      - mongo
  mongo:
    image: mongo
    # temporary workaround for
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=${MONGO_INIT_DB_ROOT_USERNAME}
      - MONGO_INIT_DB_ROOT_PASSWORD=${MONGO_INIT_DB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
